import type { Lead, Activity } from "@/types"

export const mockLeads: Lead[] = [
  {
    id: "1",
    firstName: "小明",
    lastName: "王",
    cxpName: "王小明",
    lineName: "小明的LINE",
    lineStatus: "joined",
    phone: "912345678",
    email: "wang@example.com",
    createdAt: new Date("2024-01-15"),
    avatarUrl: "/asian-man-profile.png",
    stage: "new",
    birthday: new Date("1990-05-20"),
    gender: "male",
    idNumber: "A123456789",
    city: "台北市",
    address: "信義區松仁路100號12樓",
    occupation: "高階主管",
    industry: "科技業",
    workStatus: "全職",
    carType: "new-car",
    detailCategory: "retail",
    interestedModel: "range-rover-sport",
    powerType: "gasoline",
    performancePreference: true,
    leadSource: "walk-in",
    interests: ["高爾夫", "旅遊", "品酒"],
    existingCarBrand: "BMW",
    existingCarModel: "X5",
    contactPreferences: ["mail", "email", "sms", "phone"],
    notes: "客戶對 Range Rover Sport 很感興趣，希望能試駕。",
    testDriveConsent: {
      id: "1",
      leadId: "1",
      status: "completed",
      generatedAt: new Date("2024-01-20"),
      submittedAt: new Date("2024-01-22"),
      licensePhotoFront: "/generic-identification-card-front.png",
      licensePhotoBack: "/driver-license-back.png",
      testDriveDate: new Date("2024-01-25"),
      testDriveTime: "14:30",
      vehicleBrand: "Land Rover",
      vehicleModel: "Range Rover Sport",
    },
  },
  {
    id: "2",
    firstName: "美華",
    lastName: "李",
    cxpName: "李美華",
    lineName: "",
    lineStatus: "not-joined",
    phone: "923456789",
    email: "",
    createdAt: new Date("2024-01-20"),
    stage: "follow-up",
    carType: "certified-used",
    leadSource: "referral",
    referrer: "王小明",
    contactPreferences: ["mail", "email", "sms", "phone"],
    testDriveConsent: undefined,
  },
  {
    id: "3",
    firstName: "大偉",
    lastName: "陳",
    cxpName: "陳大偉",
    lineName: "David Chen",
    lineStatus: "joined",
    phone: "934567890",
    email: "david.chen@example.com",
    createdAt: new Date("2024-02-01"),
    stage: "follow-up",
    birthday: new Date("1988-03-10"),
    gender: "male",
    idNumber: "B234567890",
    city: "新北市",
    address: "板橋區文化路一段200號",
    occupation: "企業主",
    industry: "金融業",
    workStatus: "自營",
    carType: "new-car",
    detailCategory: "retail",
    interestedModel: "i-pace",
    powerType: "electric",
    performancePreference: true,
    leadSource: "retailer-experience",
    interests: ["攝影", "科技", "戶外運動"],
    existingCarBrand: "Tesla",
    existingCarModel: "Model 3",
    contactPreferences: ["mail", "email", "phone", "sms"],
    notes: "參加過體驗活動，對電動車很有興趣。",
    testDriveConsent: {
      id: "3",
      leadId: "3",
      status: "pending",
      generatedAt: new Date("2024-02-05"),
      qrCodeUrl: "/qr-code.png",
      testDriveDate: new Date("2024-02-10"),
      testDriveTime: "10:00",
      vehicleBrand: "Jaguar",
      vehicleModel: "I-PACE",
      licensePhotoFront: "/generic-identification-card-front.png",
      licensePhotoBack: "/driver-license-back.png",
    },
  },
  {
    id: "4",
    firstName: "雅婷",
    lastName: "林",
    cxpName: "林雅婷",
    lineName: "",
    lineStatus: "not-joined",
    phone: "945678901",
    email: "",
    createdAt: new Date("2024-02-10"),
    stage: "new",
    carType: "new-car",
    leadSource: "walk-in",
    contactPreferences: ["mail", "email", "sms", "phone"],
    testDriveConsent: undefined,
  },
  {
    id: "5",
    firstName: "志明",
    lastName: "張",
    cxpName: "張志明",
    lineName: "Jimmy Chang",
    lineStatus: "joined",
    phone: "956789012",
    email: "jimmy@example.com",
    createdAt: new Date("2024-02-15"),
    avatarUrl: "/asian-businessman-meeting.png",
    stage: "lost",
    lostReason: "客戶表示預算有限，最後選擇購買其他品牌的車款。已建議客戶未來有需求時可再聯繫。",
    birthday: new Date("1987-07-08"),
    gender: "male",
    idNumber: "C345678901",
    city: "桃園市",
    address: "中壢區中央西路二段88號",
    occupation: "專業人士",
    industry: "醫療業",
    workStatus: "全職",
    carType: "certified-used",
    detailCategory: "approved-pre-owned",
    interestedModel: "defender-110",
    powerType: "diesel",
    performancePreference: true,
    leadSource: "referral",
    referrer: "陳大偉",
    interests: ["高爾夫", "品酒"],
    existingCarBrand: "Mercedes-Benz",
    existingCarModel: "GLC",
    contactPreferences: ["email", "phone"],
    notes: "預算考量，最後選擇其他品牌。",
    testDriveConsent: {
      id: "5",
      leadId: "5",
      status: "completed",
      generatedAt: new Date("2024-02-10"),
      submittedAt: new Date("2024-02-12"),
      licensePhotoFront: "/generic-identification-card-front.png",
      licensePhotoBack: "/driver-license-back.png",
      testDriveDate: new Date("2024-02-15"),
      testDriveTime: "15:00",
      vehicleBrand: "Land Rover",
      vehicleModel: "Defender 110",
    },
  },
]

export const mockActivities: Record<string, Activity[]> = {
  "1": [
    {
      id: "1",
      type: "event",
      subject: "電話聯繫，討論試駕時間",
      createdAt: new Date("2024-01-20"),
      startDateTime: new Date("2024-01-20T10:00:00"),
      endDateTime: new Date("2024-01-20T10:30:00"),
    },
    {
      id: "2",
      type: "task",
      subject: "寄送產品型錄",
      createdAt: new Date("2024-01-18"),
      dueDate: new Date("2024-01-19"),
      status: "completed",
    },
    {
      id: "3",
      type: "task",
      subject: "客戶表示下週有空可以來展間",
      description: "預約下週來店看車",
      createdAt: new Date("2024-01-16"),
      dueDate: new Date("2024-01-23"),
      status: "in-progress",
    },
  ],
  "2": [
    {
      id: "4",
      type: "event",
      subject: "初次聯繫，介紹 Defender 90",
      createdAt: new Date("2024-01-22"),
      startDateTime: new Date("2024-01-22T14:00:00"),
      endDateTime: new Date("2024-01-22T15:00:00"),
    },
    {
      id: "5",
      type: "task",
      subject: "客戶表示需要考慮預算",
      description: "待後續跟進",
      createdAt: new Date("2024-01-21"),
      dueDate: new Date("2024-01-28"),
      status: "waiting",
    },
  ],
  "3": [
    {
      id: "6",
      type: "event",
      subject: "參加體驗活動",
      createdAt: new Date("2024-02-02"),
      startDateTime: new Date("2024-02-02T09:00:00"),
      endDateTime: new Date("2024-02-02T12:00:00"),
    },
    {
      id: "7",
      type: "task",
      subject: "安排試駕",
      createdAt: new Date("2024-02-03"),
      dueDate: new Date("2024-02-10"),
      status: "completed",
    },
  ],
  "4": [
    {
      id: "8",
      type: "event",
      subject: "首次來店諮詢",
      createdAt: new Date("2024-02-10"),
      startDateTime: new Date("2024-02-10T11:00:00"),
      endDateTime: new Date("2024-02-10T12:00:00"),
    },
  ],
  "5": [
    {
      id: "9",
      type: "event",
      subject: "跟進購車意願",
      createdAt: new Date("2024-02-18"),
      startDateTime: new Date("2024-02-18T15:00:00"),
      endDateTime: new Date("2024-02-18T15:30:00"),
    },
    {
      id: "10",
      type: "task",
      subject: "客戶表示預算不足，選擇其他品牌",
      description: "標記為流失",
      createdAt: new Date("2024-02-20"),
      dueDate: new Date("2024-02-20"),
      status: "completed",
    },
  ],
}

export function getLeadById(id: string): Lead | undefined {
  return mockLeads.find((lead) => lead.id === id)
}

export function getActivitiesByLeadId(leadId: string): Activity[] {
  return mockActivities[leadId] || []
}
