import type { Lead, Activity, Opportunity, Account } from "@/types"

export const mockLeads: Lead[] = [
  {
    id: "1",
    firstName: "小明",
    lastName: "王",
    cxpName: "王小明",
    lineName: "小明的LINE",
    lineStatus: "joined",
    phone: "912345678",
    email: "wang@example.com",
    createdAt: new Date("2024-01-15"),
    avatarUrl: "/asian-man-profile.png",
    stage: "new",
    birthday: new Date("1990-05-20"),
    gender: "male",
    idNumber: "A123456789",
    city: "台北市",
    address: "信義區松仁路100號12樓",
    occupation: "高階主管",
    industry: "科技業",
    workStatus: "全職",
    carType: "new-car",
    detailCategory: "retail",
    interestedModel: "range-rover-sport",
    powerType: "gasoline",
    performancePreference: true,
    leadSource: "walk-in",
    interests: ["高爾夫", "旅遊", "品酒"],
    existingCarBrand: "BMW",
    existingCarModel: "X5",
    contactPreferences: ["mail", "email", "sms", "phone"],
    notes: "客戶對 Range Rover Sport 很感興趣，希望能試駕。",
    testDriveConsent: {
      id: "1",
      leadId: "1",
      status: "completed",
      generatedAt: new Date("2024-01-20"),
      submittedAt: new Date("2024-01-22"),
      licensePhotoFront: "/generic-identification-card-front.png",
      licensePhotoBack: "/driver-license-back.png",
      testDriveDate: new Date("2024-01-25"),
      testDriveTime: "14:30",
      vehicleBrand: "Land Rover",
      vehicleModel: "Range Rover Sport",
    },
  },
  {
    id: "2",
    firstName: "美華",
    lastName: "李",
    cxpName: "李美華",
    lineName: "",
    lineStatus: "not-joined",
    phone: "923456789",
    email: "",
    createdAt: new Date("2024-01-20"),
    stage: "follow-up",
    carType: "certified-used",
    leadSource: "referral",
    referrer: "王小明",
    contactPreferences: ["mail", "email", "sms", "phone"],
    testDriveConsent: undefined,
  },
  {
    id: "3",
    firstName: "大偉",
    lastName: "陳",
    cxpName: "陳大偉",
    lineName: "David Chen",
    lineStatus: "joined",
    phone: "934567890",
    email: "david.chen@example.com",
    createdAt: new Date("2024-02-01"),
    stage: "follow-up",
    birthday: new Date("1988-03-10"),
    gender: "male",
    idNumber: "B234567890",
    city: "新北市",
    address: "板橋區文化路一段200號",
    occupation: "企業主",
    industry: "金融業",
    workStatus: "自營",
    carType: "new-car",
    detailCategory: "retail",
    interestedModel: "i-pace",
    powerType: "electric",
    performancePreference: true,
    leadSource: "retailer-experience",
    interests: ["攝影", "科技", "戶外運動"],
    existingCarBrand: "Tesla",
    existingCarModel: "Model 3",
    contactPreferences: ["mail", "email", "phone", "sms"],
    notes: "參加過體驗活動，對電動車很有興趣。",
    testDriveConsent: {
      id: "3",
      leadId: "3",
      status: "pending",
      generatedAt: new Date("2024-02-05"),
      qrCodeUrl: "/qr-code.png",
      testDriveDate: new Date("2024-02-10"),
      testDriveTime: "10:00",
      vehicleBrand: "Jaguar",
      vehicleModel: "I-PACE",
      licensePhotoFront: "/generic-identification-card-front.png",
      licensePhotoBack: "/driver-license-back.png",
    },
  },
  {
    id: "4",
    firstName: "雅婷",
    lastName: "林",
    cxpName: "林雅婷",
    lineName: "",
    lineStatus: "not-joined",
    phone: "945678901",
    email: "",
    createdAt: new Date("2024-02-10"),
    stage: "new",
    carType: "new-car",
    leadSource: "walk-in",
    contactPreferences: ["mail", "email", "sms", "phone"],
    testDriveConsent: undefined,
  },
  {
    id: "5",
    firstName: "志明",
    lastName: "張",
    cxpName: "張志明",
    lineName: "Jimmy Chang",
    lineStatus: "joined",
    phone: "956789012",
    email: "jimmy@example.com",
    createdAt: new Date("2024-02-15"),
    avatarUrl: "/asian-businessman-meeting.png",
    stage: "lost",
    lostReason: "客戶表示預算有限，最後選擇購買其他品牌的車款。已建議客戶未來有需求時可再聯繫。",
    birthday: new Date("1987-07-08"),
    gender: "male",
    idNumber: "C345678901",
    city: "桃園市",
    address: "中壢區中央西路二段88號",
    occupation: "專業人士",
    industry: "醫療業",
    workStatus: "全職",
    carType: "certified-used",
    detailCategory: "approved-pre-owned",
    interestedModel: "defender-110",
    powerType: "diesel",
    performancePreference: true,
    leadSource: "referral",
    referrer: "陳大偉",
    interests: ["高爾夫", "品酒"],
    existingCarBrand: "Mercedes-Benz",
    existingCarModel: "GLC",
    contactPreferences: ["email", "phone"],
    notes: "預算考量，最後選擇其他品牌。",
    testDriveConsent: {
      id: "5",
      leadId: "5",
      status: "completed",
      generatedAt: new Date("2024-02-10"),
      submittedAt: new Date("2024-02-12"),
      licensePhotoFront: "/generic-identification-card-front.png",
      licensePhotoBack: "/driver-license-back.png",
      testDriveDate: new Date("2024-02-15"),
      testDriveTime: "15:00",
      vehicleBrand: "Land Rover",
      vehicleModel: "Defender 110",
    },
  },
]

export const mockActivities: Record<string, Activity[]> = {
  "1": [
    {
      id: "1",
      type: "event",
      subject: "電話聯繫，討論試駕時間",
      createdAt: new Date("2024-01-20"),
      startDateTime: new Date("2024-01-20T10:00:00"),
      endDateTime: new Date("2024-01-20T10:30:00"),
    },
    {
      id: "2",
      type: "task",
      subject: "寄送產品型錄",
      createdAt: new Date("2024-01-18"),
      dueDate: new Date("2024-01-19"),
      status: "completed",
    },
    {
      id: "3",
      type: "task",
      subject: "客戶表示下週有空可以來展間",
      description: "預約下週來店看車",
      createdAt: new Date("2024-01-16"),
      dueDate: new Date("2024-01-23"),
      status: "in-progress",
    },
  ],
  "2": [
    {
      id: "4",
      type: "event",
      subject: "初次聯繫，介紹 Defender 90",
      createdAt: new Date("2024-01-22"),
      startDateTime: new Date("2024-01-22T14:00:00"),
      endDateTime: new Date("2024-01-22T15:00:00"),
    },
    {
      id: "5",
      type: "task",
      subject: "客戶表示需要考慮預算",
      description: "待後續跟進",
      createdAt: new Date("2024-01-21"),
      dueDate: new Date("2024-01-28"),
      status: "waiting",
    },
  ],
  "3": [
    {
      id: "6",
      type: "event",
      subject: "參加體驗活動",
      createdAt: new Date("2024-02-02"),
      startDateTime: new Date("2024-02-02T09:00:00"),
      endDateTime: new Date("2024-02-02T12:00:00"),
    },
    {
      id: "7",
      type: "task",
      subject: "安排試駕",
      createdAt: new Date("2024-02-03"),
      dueDate: new Date("2024-02-10"),
      status: "completed",
    },
  ],
  "4": [
    {
      id: "8",
      type: "event",
      subject: "首次來店諮詢",
      createdAt: new Date("2024-02-10"),
      startDateTime: new Date("2024-02-10T11:00:00"),
      endDateTime: new Date("2024-02-10T12:00:00"),
    },
  ],
  "5": [
    {
      id: "9",
      type: "event",
      subject: "跟進購車意願",
      createdAt: new Date("2024-02-18"),
      startDateTime: new Date("2024-02-18T15:00:00"),
      endDateTime: new Date("2024-02-18T15:30:00"),
    },
    {
      id: "10",
      type: "task",
      subject: "客戶表示預算不足，選擇其他品牌",
      description: "標記為流失",
      createdAt: new Date("2024-02-20"),
      dueDate: new Date("2024-02-20"),
      status: "completed",
    },
  ],
}

// Mock Accounts (帳戶)
export const mockAccounts: Account[] = [
  {
    id: "acc-1",
    firstName: "小明",
    lastName: "王",
    cxpName: "王小明",
    lineName: "小明的LINE",
    lineStatus: "joined",
    phone: "912345678",
    email: "wang.xiaoming@example.com",
    convertedAt: new Date("2024-03-01"),
    avatarUrl: "/asian-man-profile.png",
    birthday: new Date("1990-05-20"),
    gender: "male",
    language: "中文(繁體)",
    nationalId: "A123456789",
    mobilePhone: "912345678",
    billingCity: "台北市",
    billingAddress: "大安區敦化南路一段100號",
    shippingCity: "台北市",
    shippingAddress: "大安區敦化南路一段100號",
    brandPreferences: ["Land Rover"],
    interestedModel: "Range Rover Sport",
    leadSource: "walk-in",
    contactPreferences: ["phone", "email"],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    occupation: "企業主管",
    industry: "科技業",
    familyMemberCount: 4,
    vehicleCount: 2,
    maintenanceStatus: "purchased",
    interests: ["高爾夫", "戶外運動", "旅遊"],
    notes: "對 Range Rover Sport 興趣濃厚，預計年底前購車。喜歡戶外運動，週末常帶家人出遊。",
  },
  {
    id: "acc-2",
    firstName: "美華",
    lastName: "李",
    cxpName: "李美華",
    lineName: "",
    lineStatus: "not-joined",
    phone: "923456789",
    email: "lee.meihua@example.com",
    convertedAt: new Date("2024-02-15"),
    birthday: new Date("1985-08-15"),
    gender: "female",
    language: "中文(繁體)",
    nationalId: "B234567890",
    mobilePhone: "923456789",
    billingCity: "新北市",
    billingAddress: "板橋區文化路二段50號",
    brandPreferences: ["Land Rover"],
    interestedModel: "Defender 90",
    leadSource: "referral",
    contactPreferences: ["email", "sms"],
    maritalStatus: "single",
    hasChildren: false,
    occupation: "設計師",
    industry: "創意產業",
    familyMemberCount: 2,
    vehicleCount: 1,
    maintenanceStatus: "interested",
    interests: ["藝術", "攝影", "露營"],
    notes: "朋友推薦來看車，對 Defender 的外型設計非常喜歡。",
  },
  {
    id: "acc-3",
    firstName: "大偉",
    lastName: "陳",
    cxpName: "陳大偉",
    lineName: "David Chen",
    lineStatus: "joined",
    phone: "934567890",
    email: "david.chen@example.com",
    email2: "david.chen.work@company.com",
    convertedAt: new Date("2024-01-20"),
    avatarUrl: "/asian-businessman-meeting.png",
    birthday: new Date("1988-03-10"),
    gender: "male",
    language: "中文(繁體)",
    nationalId: "C345678901",
    mobilePhone: "934567890",
    homePhone: "02-27001234",
    billingCity: "台中市",
    billingAddress: "西屯區台灣大道三段99號",
    shippingCity: "台中市",
    shippingAddress: "西屯區台灣大道三段99號",
    brandPreferences: ["Jaguar", "Land Rover"],
    interestedModel: "I-PACE",
    leadSource: "retailer-experience",
    contactPreferences: ["phone", "email"],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 1,
    occupation: "工程師",
    industry: "電動車產業",
    familyMemberCount: 3,
    vehicleCount: 2,
    maintenanceStatus: "purchased",
    interests: ["科技", "電動車", "環保"],
    notes: "已購入 I-PACE，對電動車非常熟悉。也對 Range Rover 有興趣，考慮作為第二台車。",
  },
]

// Mock Opportunities (機會)
export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    accountId: "acc-1",
    accountName: "王小明",
    name: "Range Rover Sport 購車",
    stage: "negotiate",
    probability: 75,
    carType: "new-car",
    detailCategory: "retail",
    interestedModel: "Range Rover Sport",
    powerType: "gasoline",
    performancePreference: true,
    leadSource: "walk-in",
    existingCarBrand: "BMW",
    existingCarModel: "X5",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "opp-2",
    accountId: "acc-1",
    accountName: "王小明",
    name: "Defender 110 換購",
    stage: "test-drive-demo",
    probability: 30,
    carType: "new-car",
    detailCategory: "retail",
    interestedModel: "Defender 110",
    powerType: "diesel",
    performancePreference: false,
    leadSource: "existing-customer",
    existingCarBrand: "BMW",
    existingCarModel: "X5",
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "opp-3",
    accountId: "acc-2",
    accountName: "李美華",
    name: "Defender 90 認證中古車",
    stage: "qualify",
    probability: 50,
    carType: "certified-used",
    detailCategory: "approved-pre-owned",
    interestedModel: "Defender 90",
    powerType: "gasoline",
    performancePreference: false,
    leadSource: "referral",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-03-05"),
  },
  {
    id: "opp-4",
    accountId: "acc-3",
    accountName: "陳大偉",
    name: "I-PACE 電動車購入",
    stage: "closed-won",
    probability: 100,
    carType: "new-car",
    detailCategory: "retail",
    interestedModel: "I-PACE",
    powerType: "electric",
    performancePreference: false,
    leadSource: "retailer-experience",
    existingCarBrand: "Tesla",
    existingCarModel: "Model 3",
    orderDate: new Date("2024-02-28"),
    deliveryDate: new Date("2024-04-15"),
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-02-28"),
  },
  {
    id: "opp-5",
    accountId: "acc-3",
    accountName: "陳大偉",
    name: "Range Rover 頂級車款",
    stage: "closed-lost",
    probability: 0,
    carType: "new-car",
    detailCategory: "retail",
    interestedModel: "Range Rover",
    powerType: "hybrid",
    performancePreference: true,
    leadSource: "retailer-experience",
    existingCarBrand: "Tesla",
    existingCarModel: "Model 3",
    lostReason: "客戶預算調整，決定先購入 I-PACE，Range Rover 計畫延後。",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-02-20"),
  },
]

// Mock Activities for Opportunities
export const mockOpportunityActivities: Record<string, Activity[]> = {
  "opp-1": [
    {
      id: "oa-1",
      type: "event",
      subject: "試駕 Range Rover Sport",
      createdAt: new Date("2024-03-10"),
      startDateTime: new Date("2024-03-10T14:00:00"),
      endDateTime: new Date("2024-03-10T15:30:00"),
    },
    {
      id: "oa-2",
      type: "task",
      subject: "報價單寄送",
      description: "準備最終報價單並寄送給客戶",
      createdAt: new Date("2024-03-12"),
      dueDate: new Date("2024-03-14"),
      status: "completed",
    },
    {
      id: "oa-3",
      type: "task",
      subject: "跟進客戶決定",
      createdAt: new Date("2024-03-15"),
      dueDate: new Date("2024-03-20"),
      status: "in-progress",
    },
  ],
  "opp-2": [
    {
      id: "oa-4",
      type: "event",
      subject: "電話討論換購方案",
      createdAt: new Date("2024-03-11"),
      startDateTime: new Date("2024-03-11T10:00:00"),
      endDateTime: new Date("2024-03-11T10:30:00"),
    },
  ],
  "opp-3": [
    {
      id: "oa-5",
      type: "event",
      subject: "來店看車",
      createdAt: new Date("2024-02-25"),
      startDateTime: new Date("2024-02-25T15:00:00"),
      endDateTime: new Date("2024-02-25T16:00:00"),
    },
    {
      id: "oa-6",
      type: "task",
      subject: "準備車況報告",
      createdAt: new Date("2024-03-01"),
      dueDate: new Date("2024-03-05"),
      status: "completed",
    },
  ],
  "opp-4": [
    {
      id: "oa-7",
      type: "event",
      subject: "簽約完成",
      createdAt: new Date("2024-02-28"),
      startDateTime: new Date("2024-02-28T11:00:00"),
      endDateTime: new Date("2024-02-28T12:00:00"),
    },
    {
      id: "oa-8",
      type: "task",
      subject: "安排交車事宜",
      createdAt: new Date("2024-03-01"),
      dueDate: new Date("2024-04-10"),
      status: "in-progress",
    },
  ],
  "opp-5": [
    {
      id: "oa-9",
      type: "event",
      subject: "客戶告��暫緩",
      createdAt: new Date("2024-02-20"),
      startDateTime: new Date("2024-02-20T16:00:00"),
      endDateTime: new Date("2024-02-20T16:30:00"),
    },
  ],
}

export function getOpportunityById(id: string): Opportunity | undefined {
  return mockOpportunities.find((opp) => opp.id === id)
}

export function getOpportunitiesByAccountId(accountId: string): Opportunity[] {
  return mockOpportunities.filter((opp) => opp.accountId === accountId)
}

export function getActivitiesByOpportunityId(opportunityId: string): Activity[] {
  return mockOpportunityActivities[opportunityId] || []
}

export function getAccountById(id: string): Account | undefined {
  return mockAccounts.find((account) => account.id === id)
}

export function getLeadById(id: string): Lead | undefined {
  return mockLeads.find((lead) => lead.id === id)
}

export function getActivitiesByLeadId(leadId: string): Activity[] {
  return mockActivities[leadId] || []
}
